version: '2'

services:
  grafana:
    image: kyloon/grafana:4.3.1-170526
    network_mode: bridge
    restart: always
    volumes:
      - /grafana/plugins:/var/lib/grafana/plugins
    ports:
      - "3000:3000"
